import type { RuntimeEvent } from "../contracts/index.ts";

export const RuntimeEventType = {
    AgentTurnEnd: "agent.turn.end",
    AgentTurnStart: "agent.turn.start",
    BlackboardDecisionRequested: "blackboard.decision.requested",
    BlackboardLeaseAcquired: "blackboard.lease.acquired",
    BlackboardLeaseReleased: "blackboard.lease.released",
    BlackboardLivelockDetected: "blackboard.livelock.detected",
    BlackboardMessageAppended: "blackboard.message.appended",
    BlackboardTurnEnd: "blackboard.turn.end",
    BlackboardTurnStart: "blackboard.turn.start",
    BlackboardWorkerEnd: "blackboard.worker.end",
    BlackboardWorkerStart: "blackboard.worker.start",
    GatewayMessageReceived: "gateway.message.received",
    GatewayStart: "gateway.start",
    ChannelLinkChanged: "channel.link.changed",
    ChannelError: "channel.error",
    McpToolCallExecuted: "mcp.tool.call.executed",
    McpToolCatalogBuilt: "mcp.tool.catalog.built",
    ProviderFallbackTriggered: "provider.fallback.triggered",
    ProviderCredentialMissing: "provider.credential.missing",
    ProviderRequestFailed: "provider.request.failed",
    SandboxToolApprovalRequested: "sandbox.tool.approval.requested",
    SandboxToolApprovalDenied: "sandbox.tool.approval.denied",
    SandboxToolDenied: "sandbox.tool.denied",
    SandboxShellHookStart: "sandbox.shell.hook.start",
    SandboxShellHookEnd: "sandbox.shell.hook.end",
    SandboxShellHookFailed: "sandbox.shell.hook.failed",
    PluginInvokeStart: "plugin.invoke.start",
    PluginInvokeEnd: "plugin.invoke.end",
    PluginInvokeFailed: "plugin.invoke.failed",
    MemoryEpisodeWritten: "memory.episode.written",
    MemoryJournalWritten: "memory.journal.written",
    MemoryConsolidationCompleted: "memory.consolidation.completed",
    MemoryConsolidationFailed: "memory.consolidation.failed",
    MemoryDecaySwept: "memory.decay.swept",
    MemoryDreamCompleted: "memory.dream.completed",
    MemoryDreamFailed: "memory.dream.failed",
    MemoryDriftRepaired: "memory.drift.repaired",
    MemoryRecallReinforced: "memory.recall.reinforced",
    MemoryContradictionFlagged: "memory.contradiction.flagged",
    MemoryFeedbackClassified: "memory.feedback.classified",
    MemoryFeedbackFailed: "memory.feedback.failed",
    MemoryProjectCandidateRecorded: "memory.project.candidate.recorded",
    MemoryProjectMemoryRecalled: "memory.project.memory.recalled",
    MemoryProjectMemoryWritten: "memory.project.memory.written",
    MemoryProjectOfferProposed: "memory.project.offer.proposed",
    MemoryProjectOfferExpired: "memory.project.offer.expired",
    MemoryProjectOfferConsumed: "memory.project.offer.consumed",
    MemorySkillOfferProposed: "memory.skill.offer.proposed",
    MemorySkillOfferExpired: "memory.skill.offer.expired",
    MemorySkillOfferConsumed: "memory.skill.offer.consumed",
    MemorySkillInstalled: "memory.skill.installed",
    MemorySkillInstallFailed: "memory.skill.install.failed",
    ProjectScaffolded: "project.scaffolded",
    ProjectScaffoldFailed: "project.scaffold.failed",
    MemoryPromptBuilt: "memory.prompt.built",
    MemoryReflectionFailed: "memory.reflection.failed",
    MemoryTurnRecorded: "memory.turn.recorded",
    MemoryWarmupComplete: "memory.warmup.complete",
    MemoryBackgroundSchedulerSkipped: "memory.background.scheduler.skipped",
    PerfTtfb: "perf.ttfb",
    PerfBuildPrompt: "perf.build_prompt",
    PerfRouteLlm: "perf.route_llm",
    PerfRedisLatency: "perf.redis_latency",
    PerfSurrealAnnLatency: "perf.surreal_ann_latency",
    PerfFastRouteEvaluated: "perf.fast_route_evaluated",
    RouteEscalated: "route.escalated",
    SkillContextBuilt: "skill.context.built",
    ProcessExit: "process.exit",
    ProcessOutput: "process.output",
    ProcessOutputTruncated: "process.output.truncated",
    ProcessRestartGiveUp: "process.restart.give_up",
    ProcessStart: "process.start",
    WorkerRegistered: "worker.registered",
    WorkerTaskEnd: "worker.task.end",
    WorkerTaskFailed: "worker.task.failed",
    WorkerTaskQueued: "worker.task.queued",
    WorkerTaskStart: "worker.task.start",
} as const;

export type RuntimeEventType = (typeof RuntimeEventType)[keyof typeof RuntimeEventType];

export const FpcEventType = RuntimeEventType;
export type FpcEventType = RuntimeEventType;

export interface EventSink {
    publish(event: RuntimeEvent): void;
}
