/**
 * Describes a project-owned WebSocket protocol envelope.
 *
 * @typeParam TPayload - Payload shape carried by the message.
 * @property id - Stable message id generated by the sender.
 * @property type - Event type such as `chat.message` or `chat.final`.
 * @property payload - Event-specific JSON payload.
 * @property timestamp - Unix timestamp in milliseconds.
 * @usage Browser test page, future Rust TUI, and SocketServerService share this contract.
 */
export interface SocketEnvelope<TPayload = unknown> {
  readonly id: string;
  readonly type: string;
  readonly payload: TPayload;
  readonly timestamp: number;
}

/**
 * Describes inbound chat message payloads.
 *
 * @property conversationId - Local continuity id, not a provider session id.
 * @property content - User message text.
 * @usage SocketServerService validates this before calling AgentRuntimeService.
 */
export interface ChatMessagePayload {
  readonly conversationId: string;
  readonly content: string;
}

/**
 * Describes server options for the Bun WebSocket adapter.
 *
 * @property host - Hostname or IP used by Bun.serve.
 * @property port - TCP port used by Bun.serve.
 * @usage Tests override the port while runtime reads `.config/config.jsonc`.
 */
export interface SocketServerOptions {
  readonly host?: string;
  readonly port?: number;
}
