/**
 * Describes one ASK question generated by the LLM.
 *
 * @property id - Stable question id within this ASK.
 * @property question - Short question text.
 * @property options - Answer options (1-3 items).
 * @usage Embedded in the ASK JSON format defined by prompts/ask.schema.md.
 */
export interface AskQuestion {
  readonly id: string;
  readonly question: string;
  readonly options: readonly AskOption[];
}

/**
 * Describes one answer option for an ASK question.
 *
 * @property id - Stable option id.
 * @property text - Option label.
 * @property recommended - Whether this is the recommended choice.
 * @usage The first option should be recommended when a clear preference exists.
 */
export interface AskOption {
  readonly id: string;
  readonly text: string;
  readonly recommended: boolean;
}

/**
 * Describes a complete ASK payload generated by the LLM.
 *
 * @property askId - Unique ASK id.
 * @property conversationId - Conversation that triggered the ASK.
 * @property turnId - Turn that triggered the ASK.
 * @property questions - Ordered questions (1-n).
 * @usage Emitted as `crystal.ask.created` signal payload.
 */
export interface AskPayload {
  readonly askId: string;
  readonly conversationId: string;
  readonly turnId: string;
  readonly questions: readonly AskQuestion[];
}

/**
 * Describes a user answer to one ASK question.
 *
 * @property askId - ASK this answer belongs to.
 * @property questionId - Question being answered.
 * @property selectedOptionId - User-selected option id.
 * @property answeredAt - Unix timestamp in milliseconds.
 * @usage Emitted as `crystal.ask.answered` signal payload.
 */
export interface AskAnswerPayload {
  readonly askId: string;
  readonly questionId: string;
  readonly selectedOptionId: string;
  readonly answeredAt: number;
}

/**
 * Describes a crystallization candidate formed from an ASK + answer pair.
 *
 * @property candidateId - Stable candidate id.
 * @property patternKey - Deterministic pattern key from namespace+subject+predicate hash.
 * @property askContext - Context that triggered the original ASK.
 * @property resolution - User's chosen resolution.
 * @property hitCount - Times this pattern has been observed.
 * @usage Emitted as `crystal.candidate.formed` or `crystal.candidate.reinforced`.
 */
export interface CrystalCandidate {
  readonly candidateId: string;
  readonly patternKey: string;
  readonly askContext: string;
  readonly resolution: string;
  readonly hitCount: number;
}

/**
 * Describes a Gem elevated from a crystallization candidate.
 *
 * @property gemId - Stable Gem id.
 * @property name - Short Gem name.
 * @property summary - LLM-generated summary of the decision pattern.
 * @property promptTemplate - Prompt template injectable into model context.
 * @property patternKey - Original pattern key from the candidate.
 * @property confidence - Current confidence from 0 to 1.
 * @property hitCount - Times this Gem has been applied.
 * @property lastMatchedAt - Unix timestamp of last match.
 * @property createdAt - Unix timestamp when elevated.
 * @property updatedAt - Unix timestamp of last modification.
 * @property status - Gem lifecycle status.
 * @usage Persisted in crystal.db and emitted as `crystal.gem.elevated`.
 */
export interface CrystalGem {
  readonly gemId: string;
  readonly name: string;
  readonly summary: string;
  readonly promptTemplate: string;
  readonly patternKey: string;
  readonly confidence: number;
  readonly hitCount: number;
  readonly lastMatchedAt?: number;
  readonly createdAt: number;
  readonly updatedAt: number;
  readonly status: "active" | "stale" | "archived";
}

/**
 * Describes an EQ dimension adjustment.
 *
 * @property dimension - EQ dimension being adjusted.
 * @property previousWeight - Weight before adjustment.
 * @property newWeight - Weight after adjustment.
 * @property reason - Short explanation for the change.
 * @usage Emitted as `crystal.eq.adjusted` signal payload.
 */
export interface EqAdjustment {
  readonly dimension: "ask_frequency" | "clarify_before_act" | "delegate_to_worker";
  readonly previousWeight: number;
  readonly newWeight: number;
  readonly reason: string;
}
